### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by gustavovargasdasilva** [Jibbow/1-wire-slave#1]
Hey, Jibbow. My name is Gustavo and I'm from Brazil. I'm implementing one-wire slave on STM32F072CBux.

I'm very interested in your project. Can you give me your contact?

Best regards, 
Gustavo.

**Comment by andizimmerer** [comment]
Hey Gustavo,
I am very pleased that you are interested! I prefer communication via this issue ;)

This project was actually used and tested in a real-life academic context and works (but has some limitations, though). So depending on your usecase we might need to adjust it a little. But no worries, I can happily assist you with this!

May I ask you what's your intended usecase?

**Comment by gustavovargasdasilva** [comment]
I'm glad you answered me. 

The usecase i'm interested is to communicate 2 stm32's. The first one act like a one-wire master as usual, and the second act like a (emulated) one-wire-slave (like ds18b20), providing some information of a temperature/humidity sensor. The reason I want this is because there are i2c sensors much cheaper than one-wire, and my device only has one-wire input available for more data.

What do you think about this solution?

**Comment by andizimmerer** [comment]
This should definitely work. I don't quite understand your system setup yet, but we used this library for a very similar problem.

Okay, so because I just dumped these two files into this repository from another project, I would suggest that you just include these two files into your own project.

Just to give you some other options, there are also two other very good libraries for doing this:
 - https://gitea.youb.fr/youen/OneWireArduinoSlave/src/branch/master/src/OneWireSlave.cpp
 - https://github.com/orgua/OneWireHub

The coding style of my library is very similar to the STM HAL library, e.g. you need to provide a `OneWireSlave_InitTypeDef`. Because this library is intended to be used with many different microcontroller brands, the `__uint32_t Pin` field is a combination of STM's `GPIOx` (first 16bit) and the actual pin number (last 16bit).

Furthermore, you need to setup two different pins: one for output and one for input signal. I couln't make it work with just one pin, but you can simply connect the two pins on the hardware side with a wire ;)

Furthermore, you need to follow the instructions in the header file. You also might need to adjust the last 5 functions from the header file. Especially `void Send_Signal(__uint32_t Pin, __uint32_t duration_in_us);` because it still uses a fixed pin.

I would suggest trying it out and playing around with the library on you own and I happily assist if you encounter any problems :)

**Comment by gustavovargasdasilva** [comment]
Hello again, Jibbow.

Your coding style is really nice. I enjoyed it. I'm confused is about the inicializations and sending new data and I have some questions.

1) In what function do I put my new data from sensors to send to one-wire master? 

2) In function OneWire_Pin_State Get_Pin_State(uint32_t Pin), I had this following error:
..\Src\onewire-slave.c(536): error:  #167: argument of type "uint16_t" is incompatible with parameter of type "GPIO_TypeDef *"
This should happened because I am not changed anything in this function and I'm not quite sure what to change... where the program call this function?

3) As I'm using STM32F072, in functions OneWireSlave_Init, Start_Time_Meassurement, Get_Elapsed_Time_In_Microseconds, I changed the TIM4 through TIM3, these two timers are 16 bits, and I think I will not have any problems, right?

If you could commit a example you used in your project on STM32Fxxx and not generic for all processors, including main.c calls, I would be happy and I think most of my questions would be answered.

**Comment by gustavovargasdasilva** [comment]
Are you still there?

**Comment by gustavovargasdasilva** [comment]
If you have some example for better use of this lib, would be nice. Thanks!

**Comment by gustavovargasdasilva** [comment]
Forgot to mention: example using this lib on STM32Fxxx.

**Comment by andizimmerer** [comment]
Sorry, for the late reply. Was really busy this weekend.

I will just go through your questions one by one:

1) There is this function called `OneWire_Send(&h1wa->OneWireSlave, your_answer, length_of_your_answer_in_bytes);`
2) Yes, this happens because STM splits the pin identifier into two parts: the GPIOx part and the actual number (both are just 16bit identifiers) whereas usually pins are defined with a 32bit value. Because this library is written for other controllers as well, I decided to use to more commonly used format of 32bit. But you can simply concatenate the two values from STM like so: `h1wa->OneWireSlave.Init.Pin = (((__uint32_t)GPIOx) << 16) | (__uint16_t)Pin` with `GPIOx` and `Pin` being the names of your 1-wire pin
3) Should work, but I am not 100% sure. Just try it out ;)

Yeah, probably you are right: I really should provide a usage example. But I am not sure if I can make it this week. But feel free to open a pull request if you got it working :)

**Comment by gustavovargasdasilva** [comment]
1-wire still not working... and I'm not sure what I did wrong. Then, I have some new questions:

1. In function 
```
OneWireSlave_Init:
{
		// 1-wire pin and address
		h1ws->Init.ROM_Address = 0x28AB20BC20BD20BE;
		h1ws->Init.Pin = ((((uint32_t)GPIOB) << 16) | (uint16_t)GPIO_PIN_1 );
}
```

Is this initialization correct? In function Get_Pin_State I still got that same error I mentioned above: ("error: #167: argument of type "uint16_t" is incompatible with parameter of type "GPIO_TypeDef *").

I adjusted the function: if(HAL_GPIO_ReadPin(HAL_GPIOx, HAL_Pin)) to 		if(HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_1)) for testing the code, but didn't work.

2. In function
 ``` 
Send_Signal:
{
       //HAL_GPIO_WritePin(OneWireOutput_GPIO_Port, OneWireOutput_Pin, GPIO_PIN_RESET);
       HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_RESET);
       
       //HAL_GPIO_WritePin(OneWireOutput_GPIO_Port, OneWireOutput_Pin, GPIO_PIN_SET);	
       HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_SET);
}
```
I'm not sure why two pins that I have to write. Can you provide me the connections you used between MCUs? (Anyway, looking at my debug, as the 1-wire has not worked yet, this function is not called yet).

I connected the 1-wire bus on master with PB1 as my 1-wire bus pin and PA0 as my output on the slave and I put a wire between PB1 and PA0.

3. In main.c I called OneWireSlave_Init this way:
```
OneWireSlave_HandleTypeDef OneWireSlave;
OneWireSlave_Init(&OneWireSlave);
```
Is this initialization correct? I'm getting external interruptions but without communication on 1-wire.

--

I'm sorry if these are some silly questions. I'm testing this library in every way and I really need this working for a college work. That's why I'm asking for an example, it would be much easier to you explain and for my understanding.

Kudos

**Comment by gustavovargasdasilva** [comment]
Hey, man! I'm still here 😜 
Could you commit some example?
Thank you for advance.

**Comment by gustavovargasdasilva** [comment]
I'm getting new data from master on my slave, but I have a few questions about the GPIO settings. 

My interruptions are working ok and they are config like this, like you mentioned in the lib:

  /*Configure GPIO pin : PA4 */
  GPIO_InitStruct.Pin = GPIO_PIN_4;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING_FALLING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

For write some data to the master, I have to configure another GPIO to output and connect this port on the one-wire bus? Would not this be a short circuit?

Again, thanks you in advance for the code. It's really great.
